POST http://localhost:3003/api/blogs/
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW5oeSIsImlkIjoiNjIwZTQzZjI2NTdmYzNlM2IzODgzYjFlIiwiaWF0IjoxNjQ1MTAyMDcyLCJleHAiOjE2NDUxMDU2NzJ9.GTSEiLXvwmmbETb33XzbZQdKVv7MzjhQ7m5jV2lVPzo

{ 
    "title": "This can be deleted",
    "author": "juanhy",
    "url": "http://www.travelbloooog2.fi"
}