POST http://localhost:3003/api/blogs/
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW5oeSIsImlkIjoiNjIxNGMzNDMxMzVkZDJjM2Y5NTY3YjAzIiwiaWF0IjoxNjQ1NTI3ODgyLCJleHAiOjE2NDU1MzE0ODJ9._twPqznj-0T0OY32l5WTubOwSynB26EeixwwrEaWigw

{ 
    "title": "This can be deleted 2",
    "author": "juanhy",
    "url": "http://www.travelbloooog2.fi"
}